mod audio;
mod commands;
mod db;
mod nlp;
mod sidecars;
mod whisper;

use std::path::PathBuf;

use tauri::Manager;

use commands::dictation::DictationState;
use db::Database;

fn app_data_dir() -> PathBuf {
    let base = dirs::data_dir().unwrap_or_else(|| PathBuf::from("."));
    base.join("lightwisper")
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let dictation_state = DictationState::new();

    tauri::Builder::default()
        // === Plugins ===
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_clipboard::init())
        .plugin(tauri_plugin_global_shortcut::Builder::default().build())
        .plugin(tauri_plugin_updater::Builder::default().build())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_process::init())
        // === Setup ===
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Debug)
                        .build(),
                )?;
            }

            let data_dir = app_data_dir();
            std::fs::create_dir_all(&data_dir)?;

            let db_path = data_dir.join("lightwisper.db");
            let database = Database::open(&db_path).expect("failed to open database");

            app.manage(database);
            app.manage(dictation_state);

            // Open settings window only if not already open
            if app.get_webview_window("settings").is_none() {
                tauri::WebviewWindowBuilder::new(app, "settings", tauri::WebviewUrl::App("index.html?panel=true".into()))
                    .title("Lightwisper — Settings")
                    .build()?;
            }

            tracing::info!("lightwisper initialized (data dir: {:?})", data_dir);

            Ok(())
        })
        // === Commands ===
        .invoke_handler(tauri::generate_handler![
            // Dictation
            commands::dictation::start_dictation,
            commands::dictation::stop_dictation,
            commands::dictation::get_recording_status,
            commands::dictation::set_model,
            commands::dictation::get_model,
            // Notes
            commands::notes::create_note,
            commands::notes::get_notes,
            commands::notes::get_note,
            commands::notes::update_note,
            commands::notes::delete_note,
            commands::notes::search_notes,
            // Transcription
            commands::transcription::save_transcription,
            commands::transcription::get_transcriptions,
            commands::transcription::delete_transcription,
            commands::transcription::clear_transcriptions,
            commands::transcription::search_transcriptions,
            // Settings
            commands::settings::save_api_key,
            commands::settings::get_api_key,
            commands::settings::delete_api_key,
            // Audio
            commands::audio::save_transcription_audio,
            commands::audio::get_audio_path,
            commands::audio::show_audio_in_folder,
            commands::audio::get_audio_buffer,
            commands::audio::delete_transcription_audio,
            commands::audio::get_audio_storage_usage,
            commands::audio::delete_all_audio,
            commands::audio::retry_transcription,
            commands::audio::update_transcription_text,
            commands::audio::get_transcription_by_id,
            commands::audio::select_audio_file,
            commands::audio::get_file_size,
            commands::audio::transcribe_audio_file,
            // Dictionary
            commands::dictionary::get_dictionary,
            commands::dictionary::set_dictionary,
            commands::dictionary::add_dictionary_word,
            commands::dictionary::remove_dictionary_word,
            commands::dictionary::undo_learned_corrections,
            commands::dictionary::get_pending_dictionary,
            commands::dictionary::get_pending_dictionary_deletes,
            commands::dictionary::get_dictionary_by_client_id,
            commands::dictionary::upsert_dictionary_from_cloud,
            commands::dictionary::mark_dictionary_synced,
            commands::dictionary::hard_delete_dictionary,
            commands::dictionary::clear_dictionary_cloud_id,
            commands::dictionary::broadcast_dictionary_updated,
            // Folders
            commands::folders::get_folders,
            commands::folders::create_folder,
            commands::folders::delete_folder,
            commands::folders::rename_folder,
            commands::folders::get_folder_note_counts,
            commands::folders::get_pending_folders,
            commands::folders::get_folder_by_client_id,
            commands::folders::upsert_folder_from_cloud,
            commands::folders::mark_folder_synced,
            commands::folders::get_folder_id_map,
            commands::folders::get_pending_folder_deletes,
            commands::folders::hard_delete_folder,
            // Actions
            commands::actions::get_actions,
            commands::actions::get_action,
            commands::actions::create_action,
            commands::actions::update_action,
            commands::actions::delete_action,
            // Whisper Models
            commands::whisper_model::check_whisper_installation,
            commands::whisper_model::download_whisper_model,
            commands::whisper_model::check_model_status,
            commands::whisper_model::list_whisper_models,
            commands::whisper_model::delete_whisper_model,
            commands::whisper_model::delete_all_whisper_models,
            commands::whisper_model::cancel_whisper_download,
            commands::whisper_model::check_ffmpeg_availability,
            commands::whisper_model::get_audio_diagnostics,
            commands::whisper_model::transcribe_local_whisper,
            commands::whisper_model::list_downloaded_models,
            commands::whisper_model::get_model_download_progress,
            commands::whisper_model::whisper_server_start,
            commands::whisper_model::whisper_server_stop,
            commands::whisper_model::whisper_server_status,
            commands::whisper_model::list_gpus,
            commands::whisper_model::set_gpu_device_index,
            commands::whisper_model::get_gpu_device_index,
            commands::whisper_model::detect_gpu,
            commands::whisper_model::get_cuda_whisper_status,
            commands::whisper_model::download_cuda_whisper_binary,
            commands::whisper_model::cancel_cuda_whisper_download,
            commands::whisper_model::delete_cuda_whisper_binary,
            commands::whisper_model::transcribe_local_parakeet,
            commands::whisper_model::check_parakeet_installation,
            commands::whisper_model::download_parakeet_model,
            commands::whisper_model::check_parakeet_model_status,
            commands::whisper_model::list_parakeet_models,
            commands::whisper_model::delete_parakeet_model,
            commands::whisper_model::delete_all_parakeet_models,
            commands::whisper_model::cancel_parakeet_download,
            commands::whisper_model::get_parakeet_diagnostics,
            commands::whisper_model::parakeet_server_start,
            commands::whisper_model::parakeet_server_stop,
            commands::whisper_model::parakeet_server_status,
            commands::whisper_model::model_get_all,
            commands::whisper_model::model_check,
            commands::whisper_model::model_download,
            commands::whisper_model::model_delete,
            commands::whisper_model::model_delete_all,
            commands::whisper_model::model_check_runtime,
            commands::whisper_model::model_cancel_download,
            commands::whisper_model::open_whisper_models_folder,
            // Agent
            commands::agent::create_agent_conversation,
            commands::agent::get_agent_conversations,
            commands::agent::get_agent_conversation,
            commands::agent::delete_agent_conversation,
            commands::agent::update_agent_conversation_title,
            commands::agent::add_agent_message,
            commands::agent::get_agent_messages,
            commands::agent::archive_agent_conversation,
            commands::agent::unarchive_agent_conversation,
            commands::agent::get_conversations_for_note,
            commands::agent::search_agent_conversations,
            commands::agent::update_agent_conversation_cloud_id,
            commands::agent::send_agent_message,
            commands::agent::start_voice_agent_dictation,
            commands::agent::agent_web_search,
            commands::agent::agent_open_note,
            commands::agent::toggle_agent_overlay,
            commands::agent::hide_agent_overlay,
            commands::agent::resize_agent_window,
            commands::agent::get_agent_window_bounds,
            commands::agent::set_agent_window_bounds,
            commands::agent::start_dictation_preview,
            commands::agent::stop_dictation_preview,
            commands::agent::dismiss_dictation_preview,
            commands::agent::complete_dictation_preview,
            commands::agent::hide_dictation_preview,
            commands::agent::resize_transcription_preview_window,
            commands::agent::acquire_recording_lock,
            commands::agent::release_recording_lock,
            commands::agent::update_agent_hotkey,
            commands::agent::update_voice_agent_hotkey,
            commands::agent::get_voice_agent_key,
            commands::agent::save_voice_agent_key,
            commands::agent::get_agent_key,
            commands::agent::save_agent_key,
            commands::agent::process_local_reasoning,
            commands::agent::check_local_reasoning_available,
            // System
            commands::system::get_openai_key,
            commands::system::save_openai_key,
            commands::system::get_anthropic_key,
            commands::system::save_anthropic_key,
            commands::system::get_gemini_key,
            commands::system::save_gemini_key,
            commands::system::get_groq_key,
            commands::system::save_groq_key,
            commands::system::get_xai_key,
            commands::system::save_xai_key,
            commands::system::get_mistral_key,
            commands::system::save_mistral_key,
            commands::system::get_corti_client_id,
            commands::system::save_corti_client_id,
            commands::system::get_corti_client_secret,
            commands::system::save_corti_client_secret,
            commands::system::get_custom_transcription_key,
            commands::system::save_custom_transcription_key,
            commands::system::get_cleanup_custom_key,
            commands::system::save_cleanup_custom_key,
            commands::system::get_ui_language,
            commands::system::save_ui_language,
            commands::system::set_ui_language,
            commands::system::get_log_level,
            commands::system::app_log,
            commands::system::get_debug_state,
            commands::system::set_debug_logging,
            commands::system::open_logs_folder,
            commands::system::get_auto_start_enabled,
            commands::system::set_auto_start_enabled,
            commands::system::get_ydotool_status,
            commands::system::get_hyprland_config_status,
            commands::system::get_post_migration_state,
            commands::system::get_oauth_protocol_registered,
            commands::system::get_oauth_protocol,
            commands::system::mark_bundle_migrated,
            commands::system::mark_bundle_migration_dismissed,
            commands::system::get_platform,
            commands::system::app_quit,
            commands::system::cleanup_app,
            commands::system::open_external,
            commands::system::paste_text,
            commands::system::hide_window,
            commands::system::show_dictation_panel,
            commands::system::check_accessibility_permission,
            commands::system::prompt_accessibility_permission,
            commands::system::read_clipboard,
            commands::system::write_clipboard,
            commands::system::check_paste_tools,
            commands::system::check_accessibility_trusted,
            commands::system::request_microphone_access,
            commands::system::check_microphone_access,
            commands::system::check_system_audio_access,
            commands::system::request_system_audio_access,
            commands::system::open_microphone_settings,
            commands::system::open_sound_input_settings,
            commands::system::open_accessibility_settings,
            commands::system::open_system_audio_settings,
            commands::system::toggle_media_playback,
            commands::system::pause_media_playback,
            commands::system::resume_media_playback,
            commands::system::auth_clear_session,
            commands::system::auth_get_token,
            commands::system::auth_set_token,
            commands::system::get_app_version,
            commands::system::proxy_xai_transcription,
            commands::system::proxy_mistral_transcription,
            commands::system::proxy_corti_transcription,
            commands::system::save_all_keys_to_env,
            commands::system::set_auto_learn_flag_enabled,
            commands::system::sync_startup_preferences,
            // Window
            commands::window::window_minimize,
            commands::window::window_maximize,
            commands::window::window_close,
            commands::window::window_is_maximized,
            commands::window::snap_to_meeting_mode,
            commands::window::restore_from_meeting_mode,
            commands::window::start_window_drag,
            commands::window::stop_window_drag,
            commands::window::set_main_window_interactivity,
            commands::window::set_notification_interactivity,
            commands::window::resize_main_window,
            commands::window::update_hotkey,
            commands::window::set_hotkey_listening_mode,
            commands::window::get_hotkey_mode_info,
            commands::window::register_cancel_hotkey,
            commands::window::unregister_cancel_hotkey,
            commands::window::register_meeting_hotkey,
            commands::window::get_dictation_key,
            commands::window::get_active_dictation_key,
            commands::window::get_effective_default_hotkey,
            commands::window::save_dictation_key,
            commands::window::get_activation_mode,
            commands::window::save_activation_mode,
            commands::window::get_stt_config,
            commands::window::get_note_recording_config,
            // Update
            commands::update::check_for_updates,
            commands::update::download_update,
            commands::update::install_update,
            commands::update::get_update_status,
            commands::update::get_update_info,
            commands::update::get_update_notification_data,
            commands::update::update_notification_ready,
            commands::update::update_notification_respond,
            // Streaming
            commands::streaming::assembly_ai_streaming_warmup,
            commands::streaming::assembly_ai_streaming_start,
            commands::streaming::assembly_ai_streaming_send,
            commands::streaming::assembly_ai_streaming_force_endpoint,
            commands::streaming::assembly_ai_streaming_stop,
            commands::streaming::assembly_ai_streaming_status,
            commands::streaming::deepgram_streaming_warmup,
            commands::streaming::deepgram_streaming_start,
            commands::streaming::deepgram_streaming_send,
            commands::streaming::deepgram_streaming_finalize,
            commands::streaming::deepgram_streaming_stop,
            commands::streaming::deepgram_streaming_status,
            commands::streaming::corti_streaming_warmup,
            commands::streaming::corti_streaming_start,
            commands::streaming::corti_streaming_send,
            commands::streaming::corti_streaming_finalize,
            commands::streaming::corti_streaming_stop,
            commands::streaming::corti_streaming_status,
            commands::streaming::meeting_transcription_prepare,
            commands::streaming::meeting_transcription_start,
            commands::streaming::meeting_transcription_send,
            commands::streaming::meeting_transcription_stop,
            commands::streaming::meeting_transcription_cancel,
            commands::streaming::dictation_realtime_warmup,
            commands::streaming::dictation_realtime_start,
            commands::streaming::dictation_realtime_send,
            commands::streaming::dictation_realtime_stop,
            // Enterprise
            commands::enterprise::get_bedrock_region,
            commands::enterprise::save_bedrock_region,
            commands::enterprise::get_bedrock_profile,
            commands::enterprise::save_bedrock_profile,
            commands::enterprise::get_bedrock_access_key_id,
            commands::enterprise::save_bedrock_access_key_id,
            commands::enterprise::get_bedrock_secret_access_key,
            commands::enterprise::save_bedrock_secret_access_key,
            commands::enterprise::get_bedrock_session_token,
            commands::enterprise::save_bedrock_session_token,
            commands::enterprise::get_azure_endpoint,
            commands::enterprise::save_azure_endpoint,
            commands::enterprise::get_azure_api_key,
            commands::enterprise::save_azure_api_key,
            commands::enterprise::get_azure_deployment,
            commands::enterprise::save_azure_deployment,
            commands::enterprise::get_azure_api_version,
            commands::enterprise::save_azure_api_version,
            commands::enterprise::get_vertex_project,
            commands::enterprise::save_vertex_project,
            commands::enterprise::get_vertex_location,
            commands::enterprise::save_vertex_location,
            commands::enterprise::get_vertex_api_key,
            commands::enterprise::save_vertex_api_key,
            commands::enterprise::test_enterprise_connection,
            commands::enterprise::process_enterprise_reasoning,
            // GCal
            commands::gcal::gcal_start_oauth,
            commands::gcal::gcal_disconnect,
            commands::gcal::gcal_get_connection_status,
            commands::gcal::gcal_get_calendars,
            commands::gcal::gcal_set_calendar_selection,
            commands::gcal::gcal_set_primary_only,
            commands::gcal::gcal_sync_events,
            commands::gcal::gcal_get_upcoming_events,
            commands::gcal::gcal_get_event,
            commands::gcal::search_contacts,
            commands::gcal::upsert_contact,
            commands::gcal::get_md5_hash,
            commands::gcal::meeting_detection_get_preferences,
            commands::gcal::meeting_detection_set_preferences,
            commands::gcal::sync_notification_preferences,
            commands::gcal::set_speaker_diarization_enabled,
            commands::gcal::set_meeting_session_speaker_config,
            commands::gcal::get_whisper_vad_config,
            commands::gcal::set_whisper_vad_config,
            commands::gcal::get_meeting_notification_data,
            commands::gcal::meeting_notification_ready,
            commands::gcal::meeting_notification_respond,
            commands::gcal::join_calendar_meeting,
            commands::gcal::get_pending_meeting_note_navigation,
            // Diarization
            commands::diarization::download_diarization_models,
            commands::diarization::get_diarization_model_status,
            commands::diarization::delete_diarization_models,
            commands::diarization::cancel_diarization_download,
            commands::diarization::get_speaker_mappings,
            commands::diarization::set_speaker_mapping,
            commands::diarization::remove_speaker_mapping,
            commands::diarization::get_speaker_profiles,
            commands::diarization::attach_speaker_email,
            commands::diarization::save_note_speaker_embeddings,
            // Notes Extra
            commands::notes_extra::process_anthropic_reasoning,
            commands::notes_extra::export_note,
            commands::notes_extra::export_transcript,
            commands::notes_extra::export_dictionary,
            commands::notes_extra::semantic_search_notes,
            commands::notes_extra::semantic_reindex_all,
            commands::notes_extra::semantic_search_conversations,
            commands::notes_extra::update_note_cloud_id,
            commands::notes_extra::note_files_set_enabled,
            commands::notes_extra::note_files_set_path,
            commands::notes_extra::note_files_rebuild,
            commands::notes_extra::note_files_get_default_path,
            commands::notes_extra::note_files_pick_folder,
            commands::notes_extra::show_note_file,
            commands::notes_extra::show_folder_in_explorer,
            commands::notes_extra::transcribe_audio_file_cloud,
            commands::notes_extra::transcribe_audio_file_byok,
            commands::notes_extra::get_referral_stats,
            commands::notes_extra::send_referral_invite,
            commands::notes_extra::get_referral_invites,
            // Sync
            commands::sync::get_pending_notes,
            commands::sync::get_pending_note_deletes,
            commands::sync::get_note_by_client_id,
            commands::sync::upsert_note_from_cloud,
            commands::sync::mark_note_synced,
            commands::sync::mark_note_sync_error,
            commands::sync::hard_delete_note,
            commands::sync::get_pending_conversations,
            commands::sync::get_pending_conversation_deletes,
            commands::sync::get_conversation_by_client_id,
            commands::sync::upsert_conversation_from_cloud,
            commands::sync::mark_conversation_synced,
            commands::sync::hard_delete_conversation,
            commands::sync::get_pending_transcriptions,
            commands::sync::get_transcription_by_client_id,
            commands::sync::upsert_transcription_from_cloud,
            commands::sync::mark_transcription_synced,
            commands::sync::get_pending_transcription_deletes,
            commands::sync::hard_delete_transcription,
            // Cloud
            commands::cloud::cloud_health_check,
            commands::cloud::cloud_transcribe,
            commands::cloud::cloud_reason,
            commands::cloud::cloud_streaming_usage,
            commands::cloud::cloud_usage,
            commands::cloud::cloud_checkout,
            commands::cloud::cloud_billing_portal,
            commands::cloud::cloud_switch_plan,
            commands::cloud::cloud_preview_switch,
            commands::cloud::cloud_api_request,
            commands::cloud::llama_cpp_check,
            commands::cloud::llama_cpp_install,
            commands::cloud::llama_cpp_uninstall,
            commands::cloud::llama_server_start,
            commands::cloud::llama_server_stop,
            commands::cloud::llama_server_status,
            commands::cloud::llama_gpu_reset,
            commands::cloud::detect_vulkan_gpu,
            commands::cloud::get_llama_vulkan_status,
            commands::cloud::download_llama_vulkan_binary,
            commands::cloud::cancel_llama_vulkan_download,
            commands::cloud::delete_llama_vulkan_binary,
            commands::cloud::notify_limit_reached,
            commands::cloud::notify_activation_mode_changed,
            commands::cloud::notify_hotkey_changed,
            commands::cloud::notify_floating_icon_auto_hide_changed,
            commands::cloud::notify_panel_start_position_changed,
            commands::cloud::notify_start_minimized_changed,
            commands::cloud::start_agent_stream,
        ])
        .run(tauri::generate_context!())
        .expect("error while running lightwisper");
}
